project:
  type: website
  output-dir: docs

website:
  title: "Olma_2023"
  navbar:
    left:
      - href: index.qmd
        text: Deskriptive Statistik
      - href: about.qmd
        text: Strukturgleichungsmodell

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    language: de

editor: visual

